name: money_control
description: It's designed to provide an intuitive budget tracking experience for users and offer a comprehensive introduction to Flutter development for students by Sagnik Bhattacharya.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_analytics:
  logger:
  flutter_hooks:
  hooks_riverpod:
  google_fonts:
  google_sign_in:
  url_strategy:
  url_launcher:
  flutter_svg:
  sign_button:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/